apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: null
  generation: 1
  labels:
    run: oncokb-core-data-4-0
  name: oncokb-core-data-4-0
  namespace: oncokb
  selfLink: /apis/extensions/v1beta1/namespaces/oncokb/deployments/oncokb-core-data-4-0
spec:
  replicas: 1
  selector:
    matchLabels:
      run: oncokb-core-data-4-0
  strategy:
    rollingUpdate:
      # We want to do a rolling updates to make sure all old instances removed before last new pod is initialized.
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: oncokb-core-data-4-0
    spec:
      containers:
        - env:
          envFrom:
            - configMapRef:
                name: oncokb-core-data-4-0
            - configMapRef:
                name: oncokb-redis-cluster-ng
            - configMapRef:
                name: oncokb-db-public-rds-oncokb-user
          image: oncokb/oncokb:3.12.13
          command: ["java"]
          args: [
            "-Dapp.name=$(APP_NAME)",
            "-Djdbc.driverClassName=com.mysql.jdbc.Driver",
            "-Djdbc.url=$(DB_URL)/oncokb_core_v4_0?useUnicode=yes&characterEncoding=UTF-8&useSSL=false",
            "-Djdbc.username=$(DB_USERNAME)",
            "-Djdbc.password=$(DB_PASSWORD)",
            "-Doncokb_transcript.token=$(ONCOKB_TRANSCRIPT_TOKEN)",
            "-Dredis.enable=true",
            "-Dredis.type=$(REDIS_TYPE)",
            "-Dredis.address=$(REDIS_ADDRESS)",
            "-Dredis.password=$(REDIS_PASSWROD)",
            "-Dredis.expiration=$(REDIS_EXPIRATION)",
            "-Dswagger_url=https://data-4-0.oncokb.org",
            "-Dsentry.stacktrace.app.packages=org.mskcc.cbio.oncokb,org.genome_nexus",
            "-Dsentry.sample.rate=0.5",
            "-Dshow_sitemaps=false",
            "-jar",
            "/webapp-runner.jar",
            "--enable-compression",
            "--port",
            "8888",
            "/app.war"
          ]
          imagePullPolicy: Always
          # use actionable variants endpoint to cache everything
          readinessProbe:
            httpGet:
              path: /api/v1/utils/allActionableVariants
              port: 8888
            initialDelaySeconds: 15
            timeoutSeconds: 10
            periodSeconds: 20
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /api/v1/utils/allActionableVariants
              port: 8888
            # wait for the pod is ready
            initialDelaySeconds: 300
            timeoutSeconds: 5
            periodSeconds: 20
            failureThreshold: 60
          name: oncokb-core-data-4-0
          ports:
            - containerPort: 8888
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 4000m
              memory: 4Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "eks-oncokb"
          effect: "NoSchedule"
      nodeSelector:
        eks.amazonaws.com/nodegroup: eks-oncokb
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: oncokb-core-data-4-0
  name: oncokb-core-data-4-0
  namespace: oncokb
  selfLink: /api/v1/namespaces/oncokb/services/oncokb-core-data-4-0
spec:
  ports:
    - port: 8888
  selector:
    run: oncokb-core-data-4-0
  type: ClusterIP
