apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eks-prod-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "http"
    nginx.ingress.kubernetes.io/rewrite-target: /
    # increae max response size to avoid 413 errors see
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    ingress.kubernetes.io/proxy-body-size: 512m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    ingress.kubernetes.io/proxy-connect-timeout: "300"
    ingress.kubernetes.io/proxy-read-timeout: "300"
    ingress.kubernetes.io/proxy-send-timeout: "300"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
spec:
  rules:
  - host: "redcap.cbioportal.aws.mskcc.org"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: eks-redcap
            port:
              number: 80
  - host: "triage.cbioportal.aws.mskcc.org"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: eks-triage
            port:
              number: 80
  - host: "triage.cbioportal.mskcc.org"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: eks-triage
            port:
              number: 80
  # TODO : adjust this so that the main msk portal is accessed through "cbioportal.mskcc.org"
  - host: "cbioportal.aws.mskcc.org"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: eks-msk
            port:
              number: 80
  # TODO : adjust this so that the main msk portal is accessed through "cbioportal.mskcc.org"
  - host: "cbioportal.mskcc.org"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: eks-msk
            port:
              number: 80
      - path: "/study/summary?id=paired_bladder_2022"
        pathType: Exact
        backend:
          service:
            name: eks-redirect-paired-bladder-2022
            port:
              number: 80
  - host: "cdd.cbioportal.aws.mskcc.org"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: eks-cdd
            port:
              number: 80
  - host: "cdd.cbioportal.mskcc.org"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: eks-cdd
            port:
              number: 80
  - host: "beta.cbioportal.aws.mskcc.org"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: eks-msk-beta
            port:
              number: 80
  - host: "beta.cbioportal.mskcc.org"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: eks-msk-beta
            port:
              number: 80
  - host: "keycloak.cbioportal.mskcc.org"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: cbioportal-keycloak-http
            port:
              number: 80
  - host: "keycloak.cbioportal.aws.mskcc.org"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: cbioportal-keycloak-http
            port:
              number: 80
  - host: "sclc.cbioportal.aws.mskcc.org"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: eks-sclc
            port:
              number: 80
  - host: "sclc.cbioportal.mskcc.org"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: eks-sclc
            port:
              number: 80
  - host: "oncotree.cbioportal.aws.mskcc.org"
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: eks-oncotree
              port:
                number: 80
  - host: "www.oncotree.mskcc.org"
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: eks-oncotree
              port:
                number: 80
  - host: "oncotree.mskcc.org"
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: eks-oncotree
              port:
                number: 80
  - host: "oncotree.info"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: eks-oncotree
            port:
              number: 80
  - host: "private.cbioportal.aws.mskcc.org"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: eks-private
            port:
              number: 80
  - host: "private.cbioportal.mskcc.org"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: eks-private
            port:
              number: 80
  - host: "session-service.cbioportal.aws.mskcc.org"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: cbioportal-session-service
            port:
              number: 80
  - host: "hgnc.cbioportal.aws.mskcc.org"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: eks-hgnc
            port:
              number: 80
  - host: "import.cbioportal.aws.mskcc.org"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: import
            port:
              number: 80
  - host: "mskinternaltest.cbioportal.aws.mskcc.org"
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: eks-msk-internal-test
              port:
                number: 80
  - host: "mskinternaltestboost.cbioportal.aws.mskcc.org"
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: eks-msk-internal-test-boost
              port:
                number: 80
  - host: "mskinternaltestbalance.cbioportal.aws.mskcc.org"
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: eks-msk-internal-test-balance
              port:
                number: 80
