apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oncokb-dev-ingress
  namespace: oncokb-dev
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/limit-rps: "100"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
spec:
  tls:
    - hosts:
        - beta.oncokb.dev
        - www.oncokb.dev
      secretName: oncokb-dev-cert
  rules:
    - host: www.oncokb.dev
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: oncokb-dev
                port:
                  number: 80
    - host: beta.oncokb.dev
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: oncokb-dev
                port:
                  number: 80
