master:
  nodeSelector:
    eks.amazonaws.com/nodegroup: eks-oncokb
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "eks-oncokb"
      effect: "NoSchedule"

replica:
  nodeSelector:
    eks.amazonaws.com/nodegroup: eks-oncokb
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "eks-oncokb"
      effect: "NoSchedule"
